name: GLOBAL VILLAGE INTERNATIONAL SCHOOL
favicon: null
layout_spectrum: 0.6214695074595511
typography_spectrum: 0.9414499313570559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.04732607374899089
  lightness: 0.8952657915651798
  saturation: 0.1662735438439995
  rhythmicContrast: 0.3143303319811821
purpose: []
